version: '3.8'

networks:
  integration-test-example:

services:
  it_test:
    image: amazoncorretto:17.0.9-alpine3.18
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lottery
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - $PWD:/app
    working_dir: /app
    networks:
      - integration-test-example
    ports:
      - "8888:8888"
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lottery
    restart: on-failure
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - integration-test-example
    ports:
      - "5432:5432"